# Generated by Django 6.0.8 on 2026-09-22 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('ktu_id', models.CharField(max_length=20, null=True, unique=True)),
                ('ph_no', models.CharField(max_length=15, null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('dob', models.DateField(null=True)),
                ('cgpa', models.FloatField(null=True)),
                ('sem', models.IntegerField(null=True)),
                ('profile_image', models.ImageField(blank=True, default='default.png', upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
