# Generated by Django 6.0.8 on 2026-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='ktu_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='ph_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
