# Generated by Django 6.0.8 on 2026-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='sem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
