# Generated by Django 6.0.8 on 2026-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_profile_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
