# Generated by Django 6.0.8 on 2026-08-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='designation',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='fullname',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='ph_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
