# Generated by Django 6.0.8 on 2026-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_alter_faculty_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
