# Generated by Django 6.0.8 on 2026-09-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='ph_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
